[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/ratings/*"
  to = "/.netlify/functions/ratings"
  status = 200
  force = true

[[redirects]]
  from = "/api/movies/*"
  to = "/.netlify/functions/movies"
  status = 200
  force = true

[[redirects]]
  from = "/api/movies"
  to = "/.netlify/functions/movies"
  status = 200
  force = true

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
