[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/reports/*"
  to = "/.netlify/functions/reports/:splat"
  status = 200

[[redirects]]
  from = "/api/reports"
  to = "/.netlify/functions/reports"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
